package com.fakestore.utils;

import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.fakestore.config.AppConfig;

/**
 * AllureEnvironmentWriter – writes an environment.properties file into the
 * Allure results directory so the Allure report overview page shows key
 * runtime details (base URL, Java version, framework versions, etc.).
 *
 * This is called once from BaseTest's @BeforeAll setup method.
 *
 * The output file location is: target/allure-results/environment.properties
 * Allure automatically picks this file up when generating the HTML report.
 */
public final class AllureEnvironmentWriter {

    // Logger for this utility class
    private static final Logger log = LoggerFactory.getLogger(AllureEnvironmentWriter.class);

    // Utility class – prevent instantiation
    private AllureEnvironmentWriter() {}

    /**
     * Writes runtime environment details to the Allure results directory.
     * Safe to call multiple times – it overwrites the file each time.
     *
     * @param allureResultsDir path to the Allure results directory (e.g. "target/allure-results")
     */
    public static void write(String allureResultsDir) {
        try {
            // Resolve the target directory path
            Path resultsDir = Paths.get(allureResultsDir);

            // Create the directory if it does not already exist
            Files.createDirectories(resultsDir);

            // Build the properties object with runtime values
            Properties props = new Properties();

            // Base URL – sourced from AppConfig (env var / system property / default)
            props.setProperty("Base.URL", AppConfig.getBaseUrl());

            // Java runtime details
            props.setProperty("Java.Version", System.getProperty("java.version", "unknown"));
            props.setProperty("Java.Vendor",  System.getProperty("java.vendor",  "unknown"));

            // OS details
            props.setProperty("OS.Name",    System.getProperty("os.name",    "unknown"));
            props.setProperty("OS.Version", System.getProperty("os.version", "unknown"));

            // Framework versions (hard-coded to match pom.xml – update if versions change)
            props.setProperty("REST.Assured.Version", "5.5.0");
            props.setProperty("JUnit.Version",        "5.11.4");
            props.setProperty("Allure.Version",       "2.29.1");

            // Resolve the full path to the environment.properties file
            Path envFile = resultsDir.resolve("environment.properties");

            // Write the properties to the file using a FileWriter
            try (FileWriter writer = new FileWriter(envFile.toFile())) {
                // Store the properties with a descriptive comment header
                props.store(writer, "Allure Environment – generated by AllureEnvironmentWriter");
            }

            log.info("Allure environment.properties written to: {}", envFile.toAbsolutePath());

        } catch (IOException e) {
            // Log the error but do not fail the test run – this is non-critical
            log.warn("Failed to write Allure environment.properties: {}", e.getMessage());
        }
    }
}
